import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
  
const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.className} antialiased bg-(--background-color)`}
      >
        {children}
      </body>
    </html>
  );
}
