"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import {
  Environment,
  CameraControls,
  Bounds,
  MeshWobbleMaterial,
  useGLTF, 
} from "@react-three/drei";
import * as THREE from "three";
import { JSX, useRef } from "react";
import {
  Bloom,
  DepthOfField,
  EffectComposer,
  Noise,
  Vignette,
  ChromaticAberration
} from "@react-three/postprocessing";

// Model partially Auto-generated by: https://github.com/pmndrs/gltfjsx

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/3d-logo.glb");
  const mesh = nodes.Curve004 as THREE.Mesh;

  const ref = useRef<THREE.Group>(null);

  useFrame(({ pointer, viewport }) => {
    const x = (pointer.x * viewport.width) / 2.5;
    const y = (pointer.y * viewport.height) / 2.5;
    if (ref.current) {
      // Smoothly interpolate the rotation instead of instant lookAt
      const targetPosition = new THREE.Vector3(x, y, 10);
      const currentQuaternion = ref.current.quaternion.clone();

      // Create a temporary object to calculate target rotation
      const tempObject = new THREE.Object3D();
      tempObject.position.copy(ref.current.position);
      tempObject.lookAt(targetPosition);

      // Smoothly interpolate between current and target rotation
      ref.current.quaternion.slerp(tempObject.quaternion, 0.1);
    }
  });

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={mesh.geometry}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <MeshWobbleMaterial
          speed={0.4}
          factor={0.5}
          color="black"
          metalness={0.5}
          roughness={0.1}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/3d-logo.glb");



export default function Logo({
  width = 400,
  height = 400,
  className,
  canControl = false,
}: {
  width?: number | string;
  height?: number | string;
  className?: string;
  canControl?: boolean;
}) {
  return (
    <div className={className} style={{ width, height }}>
      <Canvas>
        <Bounds observe clip fit margin={0.5}>
          <Model />
          <Environment preset="city" />
        </Bounds>
        {canControl && <CameraControls />}
        {/* <EffectComposer> */}
        {/* <DepthOfField /> */}
        {/* <ChromaticAberration /> */}
        {/* <Noise opacity={10} /> */}
        {/* </EffectComposer> */}
      </Canvas>
    </div>
  );
}
