"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import {
  Environment,
  CameraControls,
  Bounds,
  MeshWobbleMaterial,
  WobbleMaterialProps,
  useGLTF,
} from "@react-three/drei";
import * as THREE from "three";
import { JSX, useRef, useState } from "react";
import {
  Bloom,
  DepthOfField,
  EffectComposer,
  Noise,
  Vignette,
  ChromaticAberration,
} from "@react-three/postprocessing";

// Model partially Auto-generated by: https://github.com/pmndrs/gltfjsx

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/3d-logo.glb");
  const mesh = nodes.Curve004 as THREE.Mesh;

  const [hovered, setHovered] = useState(false);
  
  const ref = useRef<THREE.Group>(null);
  const materialRef = useRef<any>(undefined);

  useFrame(({ pointer, viewport }) => {
    const x = (pointer.x * viewport.width) / 2.5;
    const y = (pointer.y * viewport.height) / 2.5;
    if (ref.current) {
      // Smoothly interpolate the rotation instead of instant lookAt
      const targetPosition = new THREE.Vector3(x, y, 10);
      const currentQuaternion = ref.current.quaternion.clone();

      // Create a temporary object to calculate target rotation
      const tempObject = new THREE.Object3D();
      tempObject.position.copy(ref.current.position);
      tempObject.lookAt(targetPosition);

      // Smoothly interpolate between current and target rotation
      ref.current.quaternion.slerp(tempObject.quaternion, 0.1);
    }
    if (materialRef.current) {
      materialRef.current.factor = materialRef.current.factor * 0.9

      if (hovered) {
        materialRef.current.factor = materialRef.current.factor + 1.0;
      }
    }
  });

  return (
    <group {...props} dispose={null} ref={ref} >
      <mesh
        castShadow
        receiveShadow
        geometry={mesh.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        material={mesh.material}
        position={[0, 0, 0]}
        onPointerOver={() => setHovered(true)} onPointerOut={() => setHovered(false)}
      >
        <MeshWobbleMaterial
          speed={0.1}
          factor={50}
          color="black"
          metalness={0.5}
          roughness={0.1}
          ref={materialRef}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/3d-logo.glb");

export default function Logo({
  width = 400,
  height = 400,
  className,
  canControl = false,
}: {
  width?: number | string;
  height?: number | string;
  className?: string;
  canControl?: boolean;
}) {
  return (
    <div className={className} style={{ width, height }}>
      <Canvas>
        <Bounds observe clip fit margin={2}>
          <Model position={[0, 1, 0]} />
          <mesh position={[0, 0, 0]} visible={false}>
            <sphereGeometry args={[2, 64, 64]} />
          </mesh>
          <Environment preset="forest" />
        </Bounds>
        {canControl && <CameraControls />}
        <EffectComposer>
        {/* <DepthOfField /> */}
        <ChromaticAberration />
        {/* <Noise opacity={10} /> */}
        </EffectComposer>
      </Canvas>
    </div>
  );
}
